#Protege Properties
#Wed Mar 11 21:39:57 MSK 2026
filechooser.last_directory=/home/ru/clojure/ClojureProtegeIDE/pprj_base
history.projects.reopen=file\:/home/ru/clojure/ClojureProtegeIDE/pprj_examples/newspaper/newspaper.pprj,file\:/home/ru/clojure/ClojureProtegeIDE/pprj_base/ProClojure.pprj
mainframe.rectangle=384 0 1536 1040
project_chooser.selected_card=File
select_project_type.last_factory=edu.stanford.smi.protege.storage.clips.ClipsKnowledgeBaseFactory
swing.defaultlaf=com.formdev.flatlaf.FlatLightLaf
